### ISSUE TITLE
Unclear on how to set custom markers?

### ISSUE THREAD

**Issue by ErikAGriffin** [nvie/vim-flake8#101]
This may just be my unfamiliarity with vim, but I'm trying to do the following in my `.vimrc` file:
```
let flake8_error_marker='E'
let flake8_warning_marker='W'
```
and it seems to have no effect.  The error marker is still showing as an 'F>'

**Comment by nvie** [comment]
Try adding a `g:` prefix. This is a Vimscript thing where it makes it a _global_ setting, so the plugin can read it.

```
let g:flake8_error_marker='E'
let g:flake8_warning_marker='W'
```

I agree the readme is a bit unclear about this example!

**Comment by ErikAGriffin** [comment]
Ah, actually it appears either `let g:flake8_error_marker=...` or `let flake8_error_marker=...` both work.
What is happening with the `F>` appears to be that it is a PyFlakes code, [see the documentation here](https://flake8.pycqa.org/en/2.5.5/warnings.html)

Is there a way to change the marker for these PyFlakes codes @nvie?

**Comment by nvie** [comment]
Had to [re-read the source code here myself](https://github.com/nvie/vim-flake8/blob/master/autoload/flake8.vim#L89), but it looks like `flake8_pyflake_marker` is your guy — lmk if that works! If so, feel free to contribute a fix for this in the documentation 😉
