### ISSUE TITLE
Highlight/underline code with warnings/errors

### ISSUE THREAD

**Issue by st203** [nvie/vim-flake8#104]
Hello, how can I get VIM/Flake8 to highlight/underline code where there are errors/warnings in context? At the moment I have to run flake8 each time to see what the issues are (screen grab below)?

<img width="1737" alt="Screenshot 2023-01-23 at 14 00 15" src="https://user-images.githubusercontent.com/11555112/214058898-fb9d8fc5-c704-47e8-8e3c-bbad6018de77.png">

**Comment by nvie** [comment]
This is not something this plugin supports directly. This plugin will simply run the Flake8 command, and then parse/forward all reported issues in the Vim quicklist. If you want to continuously run that while typing, perhaps there is another plugin that can wrap this plugin to run it continuously on typing and highlight/underline all issues in the quickfix window?
