### ISSUE TITLE
flake8 output description gets cut off

### ISSUE THREAD

**Issue by davehouser1** [nvie/vim-flake8#106]
The plugin is not providing the full description in the vim buffer. Here is output I see after pressing F7

```
combine_md.py|74 col 5| F841 local variable 'total_size' is assigned to but neve
```

However if I run flake8 directly in linux I see the full message:

```
$ flake8 ./combine_md.py
./combine_md.py:74:5: F841 local variable 'total_size' is assigned to but never used
```

Why? anyway to fix this?

**Comment by nvie** [comment]
This plugin will not cut off the message. Maybe you have you Vim window fixed to a certain size, or another plugin is cutting off text beyond a certain number of columns?
