### ISSUE TITLE
Resolve flake8 executable through another tool per project

### ISSUE THREAD

**Issue by colindean** [nvie/vim-flake8#107]
By default, vim-flake8 expects flake8 to be on the PATH. In my usage across two orgs, flake8 isn't on the path. Rather, it's available only in poetry or pipenv contexts, e.g. `poetry run flake8` or `pipenv run flake8`. In fact, in some of my projects, we're using `flake8-pyproject` which installs a `flake8p` executable that wraps flake8 with magic to store config in `pyproject.toml`.

When I'm working in any of these projects, or if a project doesn't have flake8 installed on an active virtualenv, vim-flake8 flails.

What I'd like to see is this: if `pyproject.toml` exists and contains the string `build-backend = "poetry.core.masonry.api"` then try using `poetry run flake8`. If `Pipfile` exists, try using `pipenv run flake8`. Then fallback to just `flake8`. I'm not sure how to account for flake8p but maybe there's some way to indicate that on a per-project basis, as well, looking for evidence of `flake8-pyproject` in one of `setup.py`, `requirements.txt`, `dev-requirements.txt`, `pyproject.toml`, or `Pipfile`.

Minimally, I'd like to be able to pass a function that can do the look-up for the path and provide that somehow when vim-flake8 is initialized.

**Comment by nvie** [comment]
I consider doing all that probing out of scope for this plugin itself. However, you can define `g:flake8_cmd` yourself. Maybe the simplest and most flexible approach would be to enable Vim to allow reading per-project vim config files, by setting `set exrc` in your global Vim config, and then set `g:flake8_cmd` in each project to a value that makes sense for that project? (See `:help exrc` for more info.)

Hope that helps!
