### ISSUE TITLE
Remote file not found

### ISSUE THREAD

**Issue by daviddaiweizhang** [nvie/vim-flake8#109]
Hello,

I am editing a python script on a remote server. I opened it in VIM by

```python
e scp://username@hostname//home/username/path/to/file.py
```

but when I pressed \<F7\>, I got the following error:

```python
scp://username@hostname//home/username/path/to/file.py|| E902 FileNotFoundError: [Errno 2] No such file or directory: 'scp://username@hostname//home/username/path/to/file.py'
```

**Comment by nvie** [comment]
I don't think flake8 is capable of opening files remotely, and all this plugin does is send the filename of the buffer to flake8 and return its results.
