### ISSUE TITLE
Making vim-flake8 asynchronuous

### ISSUE THREAD

**Issue by charlax** [nvie/vim-flake8#40]
For some weird reason that I'm still debugging, when putting `autocmd BufWritePost *.py call MaybeFlake8()` flake8 runs for every single buffer on save, which takes about 4 seconds.

What's more, because flake8 is blocking, I have to wait for those 4 seconds to finish before being able to type anything.

This ticket is about making vim-flake8 asynchronous, so that we can still use vim while flake8 is running.

It seems @alfredodeza https://github.com/alfredodeza/khuno.vim implemented something similar. Any interest in doing the same?

**Comment by alfredodeza** [comment]
I don't want to hijack this issue, but fully asynchronous support is non-trivial and that was the reason I decided to do a separate plugin (vs. using or contributing to a new one). It was also infuriating to have to wait on large python files with very bad Python that made Flake8 take a while to complete.

If there is anything that is preventing you from trying Khuno.vim that I can help with, let me know. Happy to assist.

**Comment by nvie** [comment]
Thanks for chiming in, @alfredodeza. I love your vim plugin work!
@charlax, feel free to take your pick. Perhaps Khuno.vim suits your use case better. I do agree with Alfredo that making this plugin async would almost require it to be rewritten from scratch.
