### ISSUE TITLE
Quickest way to "go to next error"?

### ISSUE THREAD

**Issue by j2kun** [nvie/vim-flake8#57]
Great plugin! 

I'm wondering if there's a command I can run that quickly goes to the next line where there's a flake8 error. Right now I have to read the list of errors, spot the line number, and do `:<line number>`, but it would be nice if I could remap something like `<leader>k` to automatically jump to that line. 

How could I do this?

**Comment by nvie** [comment]
If you focus on the error window (normal Vim window movements using [`C-W j` and friends](http://vimdoc.sourceforge.net/htmldoc/windows.html#window-move-cursor)), you can just navigate to the line in question and hit `Return`. Hope that helps!

**Comment by sureshvv** [comment]
> If you focus on the error window (normal Vim window movements using [`C-W j` and friends](http://vimdoc.sourceforge.net/htmldoc/windows.html#window-move-cursor)), you can just navigate to the line in question and hit `Return`. Hope that helps!

I am just seeing the gutter on the left. How do I display the error window?

**Comment by nvie** [comment]
Hi @sureshvv, the quick answer is: you open the quickfix window with `:copen`. Here is a [StackOverflow answer](https://stackoverflow.com/a/1747286) that may be useful with some more info.

**Comment by sureshvv** [comment]
Thank you. I discovered F7 and that is working well.
