### ISSUE TITLE
vim-flake8 git version gets hold of the <F7> key unconditionally

### ISSUE THREAD

**Issue by shlomif** [nvie/vim-flake8#59]
Hi!

This page reads - https://github.com/nvie/vim-flake8

```
Customization

If you don't want to use the <F7> key for flake8-checking, simply remap it to another key. It autodetects whether it has been remapped and won't register the <F7> key if so. For example, to remap it to <F3> instead, use:

autocmd FileType python map <buffer> <F3> :call Flake8()<CR>
```

However having added  this line to my .vimrc, <F7> still does the flake8 thing instead of my previous mapping which is :cp in the quickfix window:

```
autocmd FileType python map <buffer> <F5> :call Flake8()<CR>
```

please look into correcting it because vim-flake8 does not work as advertised.

**Comment by shlomif** [comment]
I should note that one workaround I found is to add this line to my .vimrc:

```
let no_flake8_maps = 1
```

This is after studying the code.

**Comment by nvie** [comment]
Thanks @amosnier — happy to add it to the README if you want to make a PR for it! 🙏

**Comment by amosnier** [comment]
> Thanks @amosnier — happy to add it to the README if you want to make a PR for it! pray

[Done](https://github.com/nvie/vim-flake8/pull/105).

**Comment by nvie** [comment]
Thank you, @amosnier ! 🙏
