### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by sursh** [nvie/vim-flake8#61]
Hi! :) I'm trying to figure out how to customize the max line length, and the installation instructions are a little unclear on exactly which file to edit. I think the info I need should be at this link: https://flake8.readthedocs.org/en/latest/config.html but it "doesn't exist yet." Would be helpful to have a concrete example and/or fix that link for n00bs. 

Thanks for a great tool!

**Comment by sursh** [comment]
perhaps this is the new page? http://flake8.pycqa.org/en/latest/user/configuration.html

**Comment by sursh** [comment]
If anyone else is trying to do this, here's how! Put the following into your `./.config/flake8` file: 

```
[flake8]
max-line-length = 100 
```

The key concept I didn't understand from the README is that some options are set through the .vimrc (the `let g:optname=1` business) and some are set through flake8 (option names [here]( http://flake8.pycqa.org/en/latest/user/options.html#options-list)). Is that right?

**Comment by nvie** [comment]
Thanks for reporting, @sursh! This is now fixed in e0980afa8f6cef5e5e1f93ef4ffe4b01d2e048e0.

**Comment by sursh** [comment]
Great! Please also consider adding the above info to the README. This just came up again, and I had to search the issues to remember how to do this.

**Comment by nvie** [comment]
Thanks for the suggestion. This is now done in 91818a7d5f5a0af5139e9adfedc9d00fa963e699.
