### ISSUE TITLE
Screen flashes/shows terminal whenever I run flake8

### ISSUE THREAD

**Issue by peterdolan** [nvie/vim-flake8#69]
First of all, awesome plugin -- this is fantastic.

That said, having a bit of an issue. Whenever I run this plugin by hitting <f7> the terminal window pops up and it's kind of annoying/distracting.

Here's a gif of the issue: http://recordit.co/59aP65CQxL

Has anyone else had a similar problem? What was the solution?

**Comment by antoinemadec** [comment]
@peterdolan if the PR is accepted, that should fix your issue.
If the PR is not accepted, you can try my fork:
https://github.com/antoinemadec/vim-flake8

Cheers,
Antoine
