### ISSUE TITLE
:flake8 command instead of <F7> key

### ISSUE THREAD

**Issue by zubairakram** [nvie/vim-flake8#75]
It will feel very familiar to vim users if vim-flake8 executes with vim command like `:flake8` instead of hitting `<F7>` key.
Or you can make both options available. 
This is only my suggestion if this happens I am sure much more users will be happy. 

Thanks @nvie  of nice plugin.

**Comment by EmilySeville7cfg** [comment]
[vim-shellcheck](https://github.com/itspriddle/vim-shellcheck#commands) plugin adds convinient command `:[range]LShellCheck[!] [args]`. @nvie, can you implement almost the same command: `:[range]Flake[!] [args]`?
