### ISSUE TITLE
Adjusting colours

### ISSUE THREAD

**Issue by mpounsett** [nvie/vim-flake8#76]
I find the default grey-on-lightblue colour of the first listed flake8 error to be unreadable on my terminal.  I can't quite figure out from the vim-flake8 docs how to change that.  Can you make a suggestion and/or cover tweaking the colour scheme in the README?

**Comment by nvie** [comment]
The flake8 plugin only specifies that vim needs to display a message as an error or a warning. Vim then defaults to your color scheme of choice. By picking another color scheme (or tweaking your current color scheme definition), you can change your color preferences. Hope that helps!

**Comment by LeonT-A** [comment]
In the colorscheme file, what pallet section does it use?

Narrowing it down would be helpful.
