### ISSUE TITLE
Option to show Error Message of line under cursor in Vim statusbar

### ISSUE THREAD

**Issue by skvrahul** [nvie/vim-flake8#80]
It would be really useful to have an option or flag that would enable showing the error message associated with the line number which the cursor currently is on.
The error message can be displayed on the status bar
A similar feature is implemented in another package([andviro/flake8-vim](https://github.com/andviro/flake8-vim)). Attaching a screenshot below to illustrate what I mean.
![2020-03-24-135456_1600x900_scrot](https://user-images.githubusercontent.com/23026514/77404056-22f37c00-6dd7-11ea-854c-ac203ac3f888.png)

**Comment by nvie** [comment]
That would be a great addition indeed. I'd be happy to merge that feature in if you could make a pull request for this. I'm not actively adding new features to this repo myself anymore, but happy to pull new contributions in!

**Comment by skvrahul** [comment]
Sure! I'll look into it and see if I can work on that feature. Will raise a PR if and when I add it!
