### ISSUE TITLE
f-strings inside print statements are shown as invalid syntax by the flake8 linter

### ISSUE THREAD

**Issue by ayush-mandowara-bst** [nvie/vim-flake8#86]
Steps to reproduce; 
In your python file, add something like: 
` print(f"Eligible Agents: {eligible_agents}")`

[Screenshot of the error](https://prnt.sc/tuwcfo)

**Comment by ayushxx7** [comment]
+1 (I wanted to raise the issue from this account)

**Comment by nvie** [comment]
The only way I can explain this is that you're running an old version of `flake8` that doesn't recognize the new f-string syntax. This vim plugin only echoes back what it receives from invoking `flake8`. Can you verify it's actually invoking a Python 3 instance of flake8?
