### ISSUE TITLE
how can i change the indenetation as 2, so to avoid "E111 indentation is not a multipl e of four"?

### ISSUE THREAD

**Issue by nickhuangxinyu** [nvie/vim-flake8#87]
thank you for attention

**Comment by nvie** [comment]
This is not part of this vim plugin: it simply reflects what the `flake8` tool outputs. So you’ll have to figure out how to do that by configuring flake8 directly. However, it looks like [changing the indent is not supported](https://groups.google.com/forum/m/#!topic/comp.lang.python/BkiEex5RsFs) (the indent level of 4 is hardcoded).

If you really must (although I would not recommend it), you could also configure flake8 to ignore E111 errors.
