### ISSUE TITLE
ALE: Ignoring Pep8 errors in Flake8 under

### ISSUE THREAD

**Issue by eduardo4jesus** [nvie/vim-flake8#95]
I use vim-plug as plugins manager. I installed ALE and then I have flake8 and autopep8 installed.
As far as I understood, autopep8 is for fixing error automatically on save, and flake8 is to highlight the errors when file is opened or edited.

I am trying to ignore errors/warning that are shown when opening/editing the file, hence Flake8 errors, right?
I just looked in here that ``g:flake8_ignore` is deprecated.

**Comment by laoshaw** [comment]
I had flake8 under $HOME/.config and it no longer works, I had to copy that to $HOME/.flake8 and vim works again. Is the configuration location changed?

**Comment by nvie** [comment]
> I had flake8 under $HOME/.config and it no longer works, I had to copy that to $HOME/.flake8 and vim works again. Is the configuration location changed?

The location of `flake8`'s config has indeed changed. This has nothing to do with the `vim-flake8` Vim plugin though, but with `flake8` itself, which is a different project.
