### ISSUE TITLE
.config/flake8 not being picked up.

### ISSUE THREAD

**Issue by marcelofern** [nvie/vim-flake8#98]
As simple as the title says. I am using a virtualenv and neovim. But my `.config/flake8` isn't being picked up.
File content:

```
[flake8]
max-line-length = 120
```

**Comment by marcelofern** [comment]
It seems like the `.config/flake8` isn't available anymore, so you need to put it in the project root you are calling from.

**Comment by nvie** [comment]
Thx, fixed by #99! 🙏
